java -jar /software/snpEff/snpEff.jar build -genbank -v NC_045512
java -jar /software/snpEff/snpEff.jar build -genbank -v CY121682
java -jar /software/snpEff/snpEff.jar build -genbank -v MT379016
java -jar /software/snpEff/snpEff.jar build -genbank -v KU976626
java -jar /software/snpEff/snpEff.jar build -genbank -v CY122406
java -jar /software/snpEff/snpEff.jar build -genbank -v MN054138
java -jar /software/snpEff/snpEff.jar build -genbank -v MW848711
java -jar /software/snpEff/snpEff.jar build -genbank -v MK401517
java -jar /software/snpEff/snpEff.jar build -genbank -v MW269574
java -jar /software/snpEff/snpEff.jar build -genbank -v ON716232
java -jar /software/snpEff/snpEff.jar build -genbank -v CY163514
java -jar /software/snpEff/snpEff.jar build -genbank -v CY187154
java -jar /software/snpEff/snpEff.jar build -genbank -v MN873774
java -jar /software/snpEff/snpEff.jar build -genbank -v CY125864
java -jar /software/snpEff/snpEff.jar build -genbank -v CY172609
java -jar /software/snpEff/snpEff.jar build -genbank -v CY006669
java -jar /software/snpEff/snpEff.jar build -genbank -v CY021911
java -jar /software/snpEff/snpEff.jar build -genbank -v CY125030
java -jar /software/snpEff/snpEff.jar build -genbank -v KX977747
java -jar /software/snpEff/snpEff.jar build -genbank -v CY014568
java -jar /software/snpEff/snpEff.jar build -genbank -v CY091594
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180790
java -jar /software/snpEff/snpEff.jar build -genbank -v KF424052
java -jar /software/snpEff/snpEff.jar build -genbank -v MH546621
java -jar /software/snpEff/snpEff.jar build -genbank -v CY012802
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180005
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180029
java -jar /software/snpEff/snpEff.jar build -genbank -v CY179941
java -jar /software/snpEff/snpEff.jar build -genbank -v CY004594
java -jar /software/snpEff/snpEff.jar build -genbank -v MF145863
java -jar /software/snpEff/snpEff.jar build -genbank -v CY136938
java -jar /software/snpEff/snpEff.jar build -genbank -v CY137612
java -jar /software/snpEff/snpEff.jar build -genbank -v CY004484
java -jar /software/snpEff/snpEff.jar build -genbank -v CY136747
java -jar /software/snpEff/snpEff.jar build -genbank -v OP647092
java -jar /software/snpEff/snpEff.jar build -genbank -v CY061831
java -jar /software/snpEff/snpEff.jar build -genbank -v CY085704
java -jar /software/snpEff/snpEff.jar build -genbank -v MT277484
java -jar /software/snpEff/snpEff.jar build -genbank -v KF500937
java -jar /software/snpEff/snpEff.jar build -genbank -v CY159411
java -jar /software/snpEff/snpEff.jar build -genbank -v MK367185
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859232
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859056
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859064
java -jar /software/snpEff/snpEff.jar build -genbank -v CY026285
java -jar /software/snpEff/snpEff.jar build -genbank -v MK365689
java -jar /software/snpEff/snpEff.jar build -genbank -v MH134706
java -jar /software/snpEff/snpEff.jar build -genbank -v KY644188
java -jar /software/snpEff/snpEff.jar build -genbank -v DQ280218
java -jar /software/snpEff/snpEff.jar build -genbank -v DQ280251
java -jar /software/snpEff/snpEff.jar build -genbank -v EF619973
java -jar /software/snpEff/snpEff.jar build -genbank -v CY116648
java -jar /software/snpEff/snpEff.jar build -genbank -v CY017656
java -jar /software/snpEff/snpEff.jar build -genbank -v HM114587
java -jar /software/snpEff/snpEff.jar build -genbank -v MG280522
java -jar /software/snpEff/snpEff.jar build -genbank -v OP221286
java -jar /software/snpEff/snpEff.jar build -genbank -v CY031003
java -jar /software/snpEff/snpEff.jar build -genbank -v GU186787
java -jar /software/snpEff/snpEff.jar build -genbank -v GQ293082
java -jar /software/snpEff/snpEff.jar build -genbank -v KY925740
java -jar /software/snpEff/snpEff.jar build -genbank -v CY106610
java -jar /software/snpEff/snpEff.jar build -genbank -v MK839733
java -jar /software/snpEff/snpEff.jar build -genbank -v MK839805
java -jar /software/snpEff/snpEff.jar build -genbank -v HQ664926
java -jar /software/snpEff/snpEff.jar build -genbank -v CY003682
java -jar /software/snpEff/snpEff.jar build -genbank -v KY925971
java -jar /software/snpEff/snpEff.jar build -genbank -v CY036809
java -jar /software/snpEff/snpEff.jar build -genbank -v JQ689158
java -jar /software/snpEff/snpEff.jar build -genbank -v KR701370
java -jar /software/snpEff/snpEff.jar build -genbank -v AB434346
java -jar /software/snpEff/snpEff.jar build -genbank -v CY116332
java -jar /software/snpEff/snpEff.jar build -genbank -v KU322518
java -jar /software/snpEff/snpEff.jar build -genbank -v KU976534
java -jar /software/snpEff/snpEff.jar build -genbank -v AB434362
java -jar /software/snpEff/snpEff.jar build -genbank -v AB434370
java -jar /software/snpEff/snpEff.jar build -genbank -v MW848765
java -jar /software/snpEff/snpEff.jar build -genbank -v MK362699
java -jar /software/snpEff/snpEff.jar build -genbank -v CY181515
java -jar /software/snpEff/snpEff.jar build -genbank -v MF357814
java -jar /software/snpEff/snpEff.jar build -genbank -v CY186294
java -jar /software/snpEff/snpEff.jar build -genbank -v CY186004
java -jar /software/snpEff/snpEff.jar build -genbank -v KP657911
java -jar /software/snpEff/snpEff.jar build -genbank -v MH209517
java -jar /software/snpEff/snpEff.jar build -genbank -v MK071350
java -jar /software/snpEff/snpEff.jar build -genbank -v OL371233
java -jar /software/snpEff/snpEff.jar build -genbank -v FJ766839
java -jar /software/snpEff/snpEff.jar build -genbank -v CY115257
java -jar /software/snpEff/snpEff.jar build -genbank -v CY163541
java -jar /software/snpEff/snpEff.jar build -genbank -v CY187157
java -jar /software/snpEff/snpEff.jar build -genbank -v MN873777
java -jar /software/snpEff/snpEff.jar build -genbank -v CY125867
java -jar /software/snpEff/snpEff.jar build -genbank -v CY172612
java -jar /software/snpEff/snpEff.jar build -genbank -v CY006672
java -jar /software/snpEff/snpEff.jar build -genbank -v CY021914
java -jar /software/snpEff/snpEff.jar build -genbank -v CY125033
java -jar /software/snpEff/snpEff.jar build -genbank -v KX979533
java -jar /software/snpEff/snpEff.jar build -genbank -v CY004543
java -jar /software/snpEff/snpEff.jar build -genbank -v CY091591
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180793
java -jar /software/snpEff/snpEff.jar build -genbank -v KF424049
java -jar /software/snpEff/snpEff.jar build -genbank -v MH546618
java -jar /software/snpEff/snpEff.jar build -genbank -v CY012805
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180008
java -jar /software/snpEff/snpEff.jar build -genbank -v CY180032
java -jar /software/snpEff/snpEff.jar build -genbank -v CY179944
java -jar /software/snpEff/snpEff.jar build -genbank -v CY004597
java -jar /software/snpEff/snpEff.jar build -genbank -v MF147312
java -jar /software/snpEff/snpEff.jar build -genbank -v CY136941
java -jar /software/snpEff/snpEff.jar build -genbank -v KF424105
java -jar /software/snpEff/snpEff.jar build -genbank -v CY004487
java -jar /software/snpEff/snpEff.jar build -genbank -v CY136750
java -jar /software/snpEff/snpEff.jar build -genbank -v OP647089
java -jar /software/snpEff/snpEff.jar build -genbank -v CY061828
java -jar /software/snpEff/snpEff.jar build -genbank -v CY085701
java -jar /software/snpEff/snpEff.jar build -genbank -v MW000639
java -jar /software/snpEff/snpEff.jar build -genbank -v KF500934
java -jar /software/snpEff/snpEff.jar build -genbank -v CY159414
java -jar /software/snpEff/snpEff.jar build -genbank -v MK367182
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859229
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859053
java -jar /software/snpEff/snpEff.jar build -genbank -v KC859061
java -jar /software/snpEff/snpEff.jar build -genbank -v CY026288
java -jar /software/snpEff/snpEff.jar build -genbank -v MK365686
java -jar /software/snpEff/snpEff.jar build -genbank -v MH134736
java -jar /software/snpEff/snpEff.jar build -genbank -v KY644180
java -jar /software/snpEff/snpEff.jar build -genbank -v DQ280215
java -jar /software/snpEff/snpEff.jar build -genbank -v DQ280247
java -jar /software/snpEff/snpEff.jar build -genbank -v CY121685
java -jar /software/snpEff/snpEff.jar build -genbank -v MT379013
java -jar /software/snpEff/snpEff.jar build -genbank -v KU976578
java -jar /software/snpEff/snpEff.jar build -genbank -v CY122403
java -jar /software/snpEff/snpEff.jar build -genbank -v MN054134
java -jar /software/snpEff/snpEff.jar build -genbank -v MW848709
java -jar /software/snpEff/snpEff.jar build -genbank -v MK401718
java -jar /software/snpEff/snpEff.jar build -genbank -v MW269571
java -jar /software/snpEff/snpEff.jar build -genbank -v ON716229
java -jar /software/snpEff/snpEff.jar build -genbank -v KJ609205
java -jar /software/snpEff/snpEff.jar build -genbank -v KY925843
java -jar /software/snpEff/snpEff.jar build -genbank -v CY106613
java -jar /software/snpEff/snpEff.jar build -genbank -v MK839736
java -jar /software/snpEff/snpEff.jar build -genbank -v MK839808
java -jar /software/snpEff/snpEff.jar build -genbank -v HQ664923
java -jar /software/snpEff/snpEff.jar build -genbank -v CY003685
java -jar /software/snpEff/snpEff.jar build -genbank -v KY925533
java -jar /software/snpEff/snpEff.jar build -genbank -v CY036812
java -jar /software/snpEff/snpEff.jar build -genbank -v KC866602
java -jar /software/snpEff/snpEff.jar build -genbank -v CY115260